idf_component_register(
    SRCS
        "src/gw_proto_bus.c"
        "src/zb_classify.c"
        "src/rules_engine.c"
        "src/action_exec.c"
        "src/net_time.c"
    INCLUDE_DIRS
        "include"
    PRIV_REQUIRES
        esp_event
        esp_timer
        log
        esp_netif
        gw_model
        gw_proto
        gw_zigbee
        json
)

