idf_component_register(
    SRCS
        "src/storage.c"
        "src/device_registry.c"
        "src/zb_model.c"
        "src/zb_classify.c"
    INCLUDE_DIRS
        "include"
    PRIV_REQUIRES
        esp_event
        esp_timer
        log
        nvs_flash
        spiffs
        gw_zigbee
        json
)
