idf_component_register(
    SRCS
        "src/mstore_table.c"
        "src/mstore_runtime.c"
        "src/mstore_invariants.c"
        "src/mstore_ring.c"
        "src/storage/mstore_storage.c"
        "src/storage/mstore_storage_ram.c"
        "src/storage/mstore_storage_flash.c"
        "src/storage/mstore_storage_ram_flash.c"
        "port/espidf/mstore_platform_espidf.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "src"
    REQUIRES
        esp_common
        esp_partition
)
