idf_component_register(
    SRCS
        "src/gw_zigbee_support.c"
        "src/gw_zigbee_discovery.c"
        "src/gw_zigbee_actions.c"
        "src/gw_zigbee_admin.c"
        "src/gw_zigbee_events.c"
    INCLUDE_DIRS
        "include"
        "src"
    PRIV_REQUIRES
        log
        esp_timer
        gw_core
        espressif__esp-zigbee-lib
)
