#include "ha_model/ha_properties.h"

#include <stddef.h>

/*
 * Immutable словарь дескрипторов свойств (docs/PROPERTY_MODEL.md, фаза 0).
 * Только смысл: величина, единица, семантический диапазон, подсказка. Кодировки
 * транспорта (ZCL cluster/attr/scale) здесь нет — ей владеет модуль-мост.
 */

static const ha_property_desc_t PROPERTIES[] = {
    /* управляемые */
    {HA_PROPERTY_POWER, HA_VALUE_BOOL, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_BRIGHTNESS, HA_VALUE_FLOAT, HA_UNIT_PERCENT, 0.0f, 100.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_COLOR_HUE, HA_VALUE_FLOAT, HA_UNIT_NONE, 0.0f, 360.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_COLOR_SATURATION, HA_VALUE_FLOAT, HA_UNIT_PERCENT, 0.0f, 100.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_COLOR_X, HA_VALUE_FLOAT, HA_UNIT_NONE, 0.0f, 1.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_COLOR_Y, HA_VALUE_FLOAT, HA_UNIT_NONE, 0.0f, 1.0f, HA_PROPERTY_FLAG_NONE},
    {HA_PROPERTY_COLOR_TEMPERATURE, HA_VALUE_FLOAT, HA_UNIT_KELVIN, 2000.0f, 6500.0f, HA_PROPERTY_FLAG_NONE},

    /* измеряемые */
    {HA_PROPERTY_TEMPERATURE, HA_VALUE_FLOAT, HA_UNIT_CELSIUS, -100.0f, 150.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_HUMIDITY, HA_VALUE_FLOAT, HA_UNIT_PERCENT, 0.0f, 100.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_ILLUMINANCE, HA_VALUE_FLOAT, HA_UNIT_LUX, 0.0f, 100000.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_OCCUPANCY, HA_VALUE_BOOL, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_BATTERY_VOLTAGE, HA_VALUE_FLOAT, HA_UNIT_VOLT, 0.0f, 10.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_BATTERY_PERCENT, HA_VALUE_FLOAT, HA_UNIT_PERCENT, 0.0f, 100.0f, HA_PROPERTY_FLAG_READ_ONLY},

    /* синтетический системный девайс (время) */
    {HA_PROPERTY_SYSTEM_TIME_UTC, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_TIME_STATUS, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_HOUR, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 23.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_MINUTE, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 59.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_WEEKDAY, HA_VALUE_ENUM, HA_UNIT_NONE, 0.0f, 6.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_WEEKDAY_MASK, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_MINUTES_OF_DAY, HA_VALUE_U32, HA_UNIT_NONE, 0.0f, 1439.0f, HA_PROPERTY_FLAG_READ_ONLY},
    {HA_PROPERTY_SYSTEM_TZ_OFFSET, HA_VALUE_I32, HA_UNIT_MINUTE, -840.0f, 840.0f, HA_PROPERTY_FLAG_READ_ONLY},
};

/* Деградация без ложной семантики: нет записи — отдаём это. */
static const ha_property_desc_t UNKNOWN = {
    HA_PROPERTY_UNKNOWN, HA_VALUE_NONE, HA_UNIT_NONE, 0.0f, 0.0f, HA_PROPERTY_FLAG_NONE};

const ha_property_desc_t *ha_property_desc(ha_property_id_t id)
{
    const size_t count = sizeof(PROPERTIES) / sizeof(PROPERTIES[0]);
    for (size_t i = 0; i < count; i++) {
        if (PROPERTIES[i].id == id) {
            return &PROPERTIES[i];
        }
    }
    return &UNKNOWN;
}
