"""Downscale the v1 weather icons (150x150 ARGB8888 C arrays) to 40x40 LVGL 9 images.

Source icons live in ../ESP32-S3_1.5inch-lvgl/icons/*.c (generated from SVG). We don't
rasterize SVG here; we parse the existing ARGB8888 arrays and box-filter them down. The
generated files are committed, so the build does not depend on the v1 tree.

Run:  python downscale_icons.py <v1_icons_dir> <out_dir>
"""

import os
import re
import sys

SIZE = 40
LANES = 4  # ARGB8888, LVGL byte order B,G,R,A

# Исходные иконки v1 — чёрный штрих на прозрачном (для светлого фона). UI тёмный,
# поэтому красим штрих в светлый цвет, альфа сохраняет сглаживание. RGB (как байты BGRA).
TINT = (0xF9, 0xF6, 0xF3)  # ~ #F3F6F9

# symbol name -> v1 file stem
ICONS = {
    "wicon_sunny": "sunny",
    "wicon_clear_night": "clear-night",
    "wicon_partlycloudy": "partlycloudy",
    "wicon_cloudy": "cloudy",
    "wicon_overcast": "overcast",
    "wicon_fog": "fog",
    "wicon_rainy": "rainy",
    "wicon_pouring": "pouring",
    "wicon_snowy": "snowy",
    "wicon_snowy_rainy": "snowy-rainy",
    "wicon_hail": "hail",
    "wicon_lightning": "lightning",
    "wicon_lightning_rainy": "lightning-rainy",
    "wicon_windy": "windy",
    "wicon_windy_variant": "windy-variant",
    "wicon_exceptional": "alien",
}

TOKEN = re.compile(r"0x([0-9a-fA-F]{1,2})")


def parse_map(path):
    text = open(path, "r", encoding="utf-8", errors="ignore").read()
    body = text.split("_map[] = {", 1)[1].split("};", 1)[0]
    data = bytes(int(m, 16) for m in TOKEN.findall(body))
    w = re.search(r"\.header\.w = (\d+)", text)
    h = re.search(r"\.header\.h = (\d+)", text)
    return data, int(w.group(1)), int(h.group(1))


def downsample(src, sw, sh, dw, dh):
    dst = bytearray(dw * dh * LANES)
    for y in range(dh):
        y0, y1 = y * sh // dh, max(y * sh // dh + 1, (y + 1) * sh // dh)
        for x in range(dw):
            x0, x1 = x * sw // dw, max(x * sw // dw + 1, (x + 1) * sw // dw)
            sa = n = 0
            for yy in range(y0, y1):
                base = (yy * sw + x0) * LANES
                for _ in range(x0, x1):
                    sa += src[base + 3]
                    n += 1
                    base += LANES
            o = (y * dw + x) * LANES
            if sa == 0:
                continue
            dst[o], dst[o + 1], dst[o + 2], dst[o + 3] = TINT[0], TINT[1], TINT[2], sa // n
    return dst


def emit(symbol, data, size, out_dir):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    body = "\n".join(rows)
    text = f"""/* Generated by tools/downscale_icons.py from v1 icons (150x150 -> {size}x{size}). */
#include "lvgl.h"

static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_map[] = {{
{body}
}};

const lv_image_dsc_t {symbol} = {{
    .header.cf = LV_COLOR_FORMAT_ARGB8888,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = {size},
    .header.h = {size},
    .data_size = {len(data)},
    .data = {symbol}_map,
}};
"""
    with open(os.path.join(out_dir, symbol + ".c"), "w", encoding="utf-8") as f:
        f.write(text)


def main():
    v1 = sys.argv[1]
    out = sys.argv[2]
    os.makedirs(out, exist_ok=True)
    for symbol, stem in ICONS.items():
        src, sw, sh = parse_map(os.path.join(v1, stem + ".c"))
        assert len(src) == sw * sh * LANES, f"{stem}: {len(src)} != {sw*sh*LANES}"
        emit(symbol, downsample(src, sw, sh, SIZE, SIZE), SIZE, out)
        print(f"{symbol}: {sw}x{sh} -> {SIZE}x{SIZE}")


if __name__ == "__main__":
    main()
